'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Active_InActive

    '''<summary>
    '''TxtSearchActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSearchActive As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnActiveSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActiveSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GrdActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdActive As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TxtSearchInActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSearchInActive As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnInActiveSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInActiveSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GrdInActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdInActive As Global.System.Web.UI.WebControls.GridView
End Class
